# Langage utilisé
language: java

# Version du Java Development Kit à utiliser
jdk:
  - openjdk8

# Spécifications du système d'exploitation
os: linux
dist: xenial

# On spécifie une cache pour accélérer le processus du build
cache:
  directories:
    - $home/.m2

# Commandes à exécuter lors du déploiement
script:
  - java -version
  - mvn clean install
