language: java

jdk:
  - openjdk8

cache:
  directories:
    - $home/.m2

stages:
  - name: hello
    if: branch = main
    script:
      - echo "Hello from main!"
  - name: deploy
    script:
      - java -version
      - mvn clean install
