version: "3.2"
services:
  # Prometheus permet d'exposer les métriques recueillies par Cadvisor
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  # Cadvisor permet de faire le monitorage des conteneurs
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - server
  # Le conteneur server représente l'installation de OneDev
  server:
    container_name: server
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./onedev:/opt/onedev"
    ports:
      - "6610:6610"
      - "6611:6611"
    image: "1dev/server:4.2.4"
    # Les lignes qui suivent permettent de limiter les ressources
    # disponibles pour le conteneur de OneDev
    deploy:
      resources:
        limits:
          cpus: 1 # Nombre de CPUs disponibles
          memory: 512M # Mémoire disponible en mégabits
